### ISSUE TITLE
Bug with inviting people & sql doesn't work

### ISSUE THREAD

**Issue by iaxedu** [AlessioDP/Parties#10]
Hey,

Got this bug when trying to invite anyone really. No errors, parties 2.0.0 ofc. Clean default config.
https://i.imgur.com/WGBKCNY.png

Basically, invite someone and try to accept it. It will say that you're already in a party but when you do /party info it says you're not in a party.

Now with MySQL, I realise that I can fix this myself but I doubt this was intended since the average database will deny this.
https://hastebin.com/ofugeqikiw.vbs

**Comment by AlessioDP** [comment]
Can you attach your configuration related to the SQL database?

**Comment by AlessioDP** [comment]
Should be fixed now, with 2.0.1 ;)

**Comment by iaxedu** [comment]
Invite is fixed but the tables ignore the 255 setting D:

**Comment by AlessioDP** [comment]
That depends on your database settings. For example, if you are using an `utf8mb4`, the limit is 128. I don't know how your database is structured but it's probably a problem like that, you can try to set it to `128` (remember that Parties need to re-create the config.yml to let you set `varchar-size` ;))
