### ISSUE TITLE
FeatureRequest: Vault economy syncing

### ISSUE THREAD

**Issue by TheBlankSlate** [AlessioDP/Parties#101]
Hey! I think It would be super helpful if you were able to sync the economy of all of the members of the party.
For example:
you have 4 people in one party
John - $2
May - $7
Matt - $90
Mark - $100

The plugin should see that Mark has the highest amount so it will set all the other three people to $100

**Comment by AlessioDP** [comment]
I added this feature in my to do list but I don't think I will implement it.

There are so many problems to handle, this would work only on some specific server so is better to make a custom plugin to do it.
Just some problems that comes in my mind:
* how to set the money, when someone change money automatically set the highest one to everyone, be careful to do not make an infinite loop
* will it work with other plugins?
* people can duplicate money by send them to another player
* what happens on party disband and kick?
* one player use the money, everyone should lose money or he will return to 100$ again

As you can see there are so many problems that depends on how the server is set, it would be a cool feature but only if you implement it in your own server, with a custom plugin.
