### ISSUE TITLE
Database conversion from 1.7.6 to 2.1.3 

### ISSUE THREAD

**Issue by Sandukhan** [AlessioDP/Parties#12]
Hello Alessio,
i finaly updated parties from 1.7.6 to 2.1.3. However the playerdata hasnt update correctly, because timestamp and name are missing from any player that hasnt joined the server after update. They shown as a bunch of "null" in the party memberlist/info. The data yml looks something like these:

>   09bf5ca3-860d-43b3-871c-3acc9d1d2c3e:
    party: Nemesis
    rank: 5
  425f8773-d4b1-4dc1-9219-c42ffea48db0:
    party: JederNurEinKreuz
    rank: 5
  487c2025-bd0f-4a16-afa4-15cc5c9ee1d4:
    party: Zerberus
    rank: 10
    name:
       name: LordSandukhan
       timestamp: 1514961828
  d173ecb2-ada5-4795-9c37-25037ac4cb43:
    party: Rowen
    rank: 5

I was wondering if i have to update these manualy or is there any way to convert the yml correcly? Im also going to send you a new translated message-file in german for 2.1.3 in the next couple of days. Havent got much time latly, otherwise i would done these earlier.

**Comment by AlessioDP** [comment]
Hi, I will explain the problem and how I fix that with a name system.
When a player join, the server will save its data inside "playerdata" folder of the map, if you delete these folder I cannot get the name of the player. For that I started to save the player name and the timestamp of its last login to make a better list of players with old names.

When there is a list of players my plugin will follow this order to get the name of the player:
1. Get the name from the database (In this case it will return null, so it will continue to the 1b step)
1b. Get the name from the playersdata folder
2. Compare it with Mojang API to see if the name its changed

Usually when I player join, automatically it will be updated the name and timestamp values. So you just need to wait that the players join into the server.

I was investigating on that but I need a complete log of the problem, can you attach a log of the server, or parties only, with the debug level set on 3? You can find how enable it here: https://github.com/AlessioDP/Parties/wiki/How-to-report-a-bug#enable-the-debug-log

**Comment by Sandukhan** [comment]
I have send you a email with all files you need, also because i run in some more issues.
First, the log.txt dosnt seems to work correcly, because everytime something gets loged, the first line gets overwritten and no new ones been created.

Secound, the rank based permissions party.edit.desc and party.home seems to be in conflict. Players without the party.edit.desc permission in their party rank, cant use /party home. I tested that with the default setup of parties and as soon as a party home has been created, normal members cant use /party home. And no i didnt messed/forgot up the plugin permissions ;P

**Comment by AlessioDP** [comment]
Perfect, fixed everything, just wait for the release :P

Thank you for the report! The bug about the home command was so hard to catch :D
