### ISSUE TITLE
Offline players can't be removed

### ISSUE THREAD

**Issue by tommasobenatti** [AlessioDP/Parties#163]
Hi, I noticed that offline players can't be removed, can you make possible to remove players that are offline?

**Comment by AlessioDP** [comment]
Did you install LastLoginAPI? The plugin is not able to get an offline player UUID by its name without LLAPI installed.

**Comment by tommasobenatti** [comment]
No, thanks

**Comment by tommasobenatti** [comment]
couldn't you just check from essentials or luckperms api? @AlessioDP

**Comment by tommasobenatti** [comment]
ah bella sei italiano

**Comment by AlessioDP** [comment]
Not sure if I can use those plugins but LastLoginAPI is meant to be used for that reason, and its used by all other my plugins too.
