### ISSUE TITLE
Cannot save parties home

### ISSUE THREAD

**Issue by waiching514** [AlessioDP/Parties#169]
When player using /clan sethome, message displayed "sethome succes!"
but It will not save at sql database, player using /clan home, will not teleporting to home
![image](https://user-images.githubusercontent.com/29138111/152088212-a4e04c2d-358c-4873-a4a9-a4806897130d.png)

**Comment by AlessioDP** [comment]
Can you attach your server log? (Do not use plugman to load Parties)
Are you using Parties in BungeeCord or only Spigot?

**Comment by waiching514** [comment]
I'm using BungeeCord 
[11:26:41 INFO]: [Parties] WaichingXD performed the command 'SETHOME' with 0 arguments
[11:26:41 INFO]: [Parties] Sent a packet of type 'ADD_HOME' via the player * via the channel 'parties:sub'
[11:26:41 INFO]: [Parties] Got party MCSBS from list
[11:26:41 INFO]: [Parties] WaichingXD set the home of MCSBS with name default

**Comment by AlessioDP** [comment]
Its because Spigot and BungeeCord are not sync correctly, be sure to follow this guide: https://alessiodp.com/docs/parties/bungeecord

Basically, Bungee sends a packet to Spigot, asking to save the home.

**Comment by waiching514** [comment]
But other data can be saved only home can not
![image](https://user-images.githubusercontent.com/29138111/152089688-b6234acd-ad2c-4e27-ad37-5027034d4bb2.png)

**Comment by AlessioDP** [comment]
Attach the server log of the spigot server.

**Comment by waiching514** [comment]
![image](https://user-images.githubusercontent.com/29138111/152094596-934c383a-c88f-47a6-beed-53fd0cf76509.png)

**Comment by AlessioDP** [comment]
I need both logs (since the reload of Parties) of Spigot and the Bungeecord.

**Comment by waiching514** [comment]
Spigot: https://pastebin.com/un4MvtRb
Bungeecird: https://pastebin.com/7L3aWvjp

**Comment by AlessioDP** [comment]
Can I see the `config.yml`? (Be sure to do not share database credentials)

**Comment by waiching514** [comment]
https://pastebin.com/mLWx9k4k

**Comment by AlessioDP** [comment]
I will fix it for the next update

**Comment by AlessioDP** [comment]
Fixed with 3.2.0
