### ISSUE TITLE
Problem with /party home and /party confirm

### ISSUE THREAD

**Issue by Sandukhan** [AlessioDP/Parties#18]
Hi Alessio,
i got some bugs for you to fix with your new version of parties (2.2.6). ;P

1. Nocheatplus seems to cancel the teleport event of /parties home when somebody tries to use this outside of the server main world.

https://pastebin.com/9zBd7tQC
(nocheatplus 3.15.2-SNAPSHOT-sMD5NET-b1113)

2. /parties confirm dosent seems to work at all, its just doing nothing. 

3. The notification for party members going offline is showing twice, if somebody got a bad connection or get kick from console.

4.I think for the "teleport" string, is the "wrong-command" message missing, not sure you did that on purpose.

Thats it for now, looks like you also need a new german translation, i can do that next week i think.

**Comment by AlessioDP** [comment]
Fixed everything ;)
Not sure about NCP bug.

About the 4, there is no wrong command because its a simple command: /party teleport

Incoming with 2.2.8.
