### ISSUE TITLE
Cannot save parties home

### ISSUE THREAD

**Issue by waiching514** [AlessioDP/Parties#185]
When player using /clan sethome, message displayed "sethome succes!"
but It will not save at sql database, player using /clan home, will not teleporting to home
![image](https://user-images.githubusercontent.com/29138111/161187981-a854438a-56e6-42b1-822e-d0e09c252d71.png)
![image](https://user-images.githubusercontent.com/29138111/161188046-53c6a97c-56c8-46de-85fe-a7cf4dcc4fa8.png)

proxy config:
https://pastebin.com/8GKyRrgV

banked server config:
https://pastebin.com/eZzKqJVz

proxy and banked server debug log:
https://pastebin.com/0xruGZ7U

**Comment by AlessioDP** [comment]
Bungeecord packet settings are all set to false, packets won't be handled in your case.

Once changed, try to execute `/party debug bungeecord` in Spigot console and screenshot the result.

**Comment by waiching514** [comment]
[12:14:00 INFO]: Sent a debug BungeeCord request into the network

proxy server dose not respond anything

**Comment by AlessioDP** [comment]
What about packets settings? Anyway, I need both server logs with debug enabled.
Firstly, you must have at least one player in the spigot server, so keep one player there and run party debug bungeecord in console.

**Comment by waiching514** [comment]
Bungeecord and banked server packet settings are all set to false
I had keep one player  and run party debug bungeecord in banked server console.

**Comment by AlessioDP** [comment]
You need at least one player yes, but those packet settings must be set on TRUE, not false, or its normal for it to do not work.
If you set them to false, packets won't be handled at all so they are not sync.

**Comment by waiching514** [comment]
proxy and banked server both set packet to true?

**Comment by AlessioDP** [comment]
Yes

**Comment by waiching514** [comment]
[07:58:36 INFO]: Sent a debug BungeeCord request into the network
[07:58:36 INFO]: [Parties] Parties is synced correctly

**Comment by AlessioDP** [comment]
Try again the sethome command, it couldn't work before if you set those options to false.

**Comment by waiching514** [comment]
it succses to save home, but I try /home is not working

**Comment by AlessioDP** [comment]
Can I see the log of that?

**Comment by waiching514** [comment]
proxy console: [08:08:49] [Parties Pool Thread #430/INFO] [Parties]: WaichingXD performed the command 'HOME' with 0 arguments

banked server not have any respond

**Comment by AlessioDP** [comment]
Fixed with 3.2.4 ;)
