### ISSUE TITLE
[Bug Report] /party create is not in /party help

### ISSUE THREAD

**Issue by Folas1337** [AlessioDP/Parties#195]
If you type "/party help" there is no mention of "/party create <name>" and neither "/p <msg>", might wanna look into that 😄

**Comment by AlessioDP** [comment]
Can you screenshot the chat?
You won't see those commands if you do not have the permission to execute them.

**Comment by Folas1337** [comment]
Oh right, you can't see it while in a party, my fault! Thanks for looking into the other one though :) It might have also been my fault cause I commented it out in the config.yml.
Sorry if I've bothered you unnecessarily ☹️
