### ISSUE TITLE
Possible conflict with PlotSquared

### ISSUE THREAD

**Issue by JamesMCL44** [AlessioDP/Parties#196]
Parties version: 3.2.6
PlotSquared version: PlotSquared-Bukkit-6.9.2-SNAPSHOT
Server Jar version: paper-1.19 dev#43

Trigger: Both plugins enabled and run command "/plot" or with any subcommand after

Result: Return error for op user as "you are not in a party"; for non-op user as "no permission"

Further info:
After I disabled the Parties plugin, the command "plot" as well as related subcommand work again for Plotsquared.

Possible direction:
An unintentional override by command "/p"

If you need further info, please contact me at Discord JamesMCL44#871

**Comment by AlessioDP** [comment]
Hello, this is a known behavior because /p is already used by PlotSquared.

You can change Parties /p into something else at the end of `config.yml`.

**Comment by JamesMCL44** [comment]
I believe there could possible improvement to actually avoid the "conflict" mentioned in my first post.

As i mentioned in my first post, the error was caused by the command starting with "/plot". Although i understand /p is one of the alias of PlotSquared, there could be an improvement in executing the command.

Reason:
I especially draw your attention that I used "/plot" (as well as "plot2" and "plotme") NOT "/p" to execute plotsquared commands.
but it results as overridden by Parties.
The reason behind could be that Parties only detect command including "/p" but not "/p " (with a space afterwards) and therefore overridden all other commands starting with "/p".

Suggestion:
Based on that possible logic above, if that is actually the case, I would suggest to improve the command testing portion to "/p "(with a space afterwards) and same for other usable alias like "/g" for guild or any user defined ways, and the conflict in my first post could even considered as non-conflict anymore.

**Comment by AlessioDP** [comment]
No, my plugin only handles /party and /p.
That happens because as you said, its PlotSquared that have /p as alias, so when Parties registered, overriding, the command /p, it did override unintentionally the entire /plot command.

PlotSquared handles commands like that so this happens.

I will re-close this issue because its not actually an issue and you need to change /p into something else to make it work.

**Comment by AlessioDP** [comment]
Just to be clearer.
My plugin registers those commands directly into the server, it doesn't just listen to `/party` or `/p` at the start of the command.
In fact, if you run `/pardon` or `/playsound`, it won't trigger `/p` at all.
