### ISSUE TITLE
Empty file nullparties.yml

### ISSUE THREAD

**Issue by ChrissW-R1** [AlessioDP/Parties#199]
On server start, the plugin generates a file in the root directory of the server. This file is named `nullparties.yml` and is empty.

We use PaperMC 1.19-77 and Parties 3.2.6 on a Linux server.

**Comment by AlessioDP** [comment]
Can you post the full server log please

**Comment by ChrissW-R1** [comment]
I posted a log on Pastebin.com:
https://pastebin.com/d2TwUhqd

**Comment by AlessioDP** [comment]
I do not see any Parties error, maybe that file is not generated by my plugin.
Try to post the full server log, not only Parties one.
