### ISSUE TITLE
[Feature Request]     GUI`s

### ISSUE THREAD

**Issue by MysticCity** [AlessioDP/Parties#20]
Can you add some new GUIS:

1 for member like /guild and there we have all funktions for members (deposit list and and and)
2 for admins with buttons (all funktions just in a gui)
3 memberlist a list with all members with infos

**Comment by AlessioDP** [comment]
I'm working on a GUI interface for Parties :)
Thank you for the tips!

It will be a little bit advanced so it will take some time, just wait for the release ;)
