### ISSUE TITLE
SkillAPI Exp isn't distributed in newer versions

### ISSUE THREAD

**Issue by RacerN2O** [AlessioDP/Parties#21]
Since we've updated Parties to 2.2.X versions, the SkillAPI experience isn't shared anymore.

We're using SkillAPI Premium, with the setting that "converts" normal exp into SkillAPI exp (use-exp-orbs: 'true') and MythicMobs that drop those default Minecraft exp.

Parties used to work with that, but it doesn't anymore since some update. We used to use much older versions. It seems unable to recognize the SkillAPI portion of the exp now.

[Log](https://drive.google.com/open?id=1IcNnKiP9B-AVklhlpGFej62DwhdfTZwT)
[Config.yml](https://drive.google.com/open?id=1jYHmNNlMR_jLSCwnggOIc2NkI76UP0uP)
[Parties.yml](https://drive.google.com/open?id=12GeHTFwNqKwvsGczsjauQJAnKoVbCA85)

**Comment by AlessioDP** [comment]
Thank you for the report :)

Parties doesn't support MythicMobs right now (explained on the changelog on SpigotMC), are you talking about vanilla mobs or customized one?

**Comment by AlessioDP** [comment]
Let me know if you find a version that works in 2.2.X, anyway I think I will try to improve it a little bit with 2.3 version. I'm already working on it ;)

**Comment by RacerN2O** [comment]
I didn't try all the versions but I rolled all the way back to 1.7.6 which I'm pretty certain about working (couldn't test yet but I remember it working). Anything 2.X I've tried seemed not to work for us.

**Comment by AlessioDP** [comment]
I will try to handle it better in 2.3.0 ;)

**Comment by RacerN2O** [comment]
I have been messing around with the old 1.7.6 version and it's not really working as it should either. We'll distribute EXP from bosses with a different method that works just fine but is a bit of a workaround. The plugin is still very useful for other things!

**Comment by AlessioDP** [comment]
I've changed that method since 2.0 because it wasn't working properly ;)
I've added it into my to-do list for the version 2.3 ;)
