### ISSUE TITLE
Feature Request and maybe bug fix idk

### ISSUE THREAD

**Issue by Klmar** [AlessioDP/Parties#211]
pls update for ProSkillAPI unlike SkillAPI ProSkillApi is still maintained

links:

spigot: https://www.spigotmc.org/resources/proskillapi-create-custom-races-classes-skills-spells-with-an-easy-online-editor.91913/

github: https://github.com/promcteam/proskillapi

**Comment by AlessioDP** [comment]
Hello, SkillAPI is not supported at all. Maybe you are referring to the old version of Parties (the experience share is not supported anymore).
