### ISSUE TITLE
party.delete() prints error

### ISSUE THREAD

**Issue by No1Evil** [AlessioDP/Parties#218]
On api.getParty("anyParty").delete() it prints an error.

> java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "com.alessiodp.parties.common.players.objects.PartyPlayerImpl.getPlayerUUID()" because "kicked" is null

**Comment by AlessioDP** [comment]
Can you test with latest version, if not please provide the full error stack trace.

**Comment by AlessioDP** [comment]
Fixed with 3.2.9
