### ISSUE TITLE
Show heal of every players in your parties

### ISSUE THREAD

**Issue by Tiplish** [AlessioDP/Parties#23]
Hi, 

Is it possible to show the heal of every players in your party?

If it's with the tab, it overwrite every tablist system?

Thanks for the answer :)

**Comment by AlessioDP** [comment]
Hi,
It's possible to see the heal but not via the tablist. Work with tablist is a lot complicated since 1.8, I need to use ProtocolLib to make it works but it would broke every other tablist plugin and skins of players :S 

For that I removed tablist support ;)

**Comment by Tiplish** [comment]
So, with what we could see the life? ^^"

**Comment by AlessioDP** [comment]
Into the chat ;)

Maybe, but not sure, via a Scoreboard system.

**Comment by Tiplish** [comment]
I use scoreboard for skillapi so chat would be nice o/ I could see how in the config?

**Comment by AlessioDP** [comment]
A feature like that doesn't exists.
But the problem with a scoreboard system is that **only one plugin** can use the scoreboard.

In fact, if I make a scoreboard that show every player heal and maybe other things, you need to disable every other plugin that use the scoreboard, because the current scoreboard is handled by Parties.
That is the big problem of the scoreboard system :S

**Comment by Tiplish** [comment]
I understand. If i summerise there is 3 possibility :
- Use tablist (but very hard)
- Use chat (but it could hide if player speak)
- Use scoreboard (but we have to disable others plugins.

But for the moment, there is not this kind of possibility. That's it?

**Comment by AlessioDP** [comment]
1. Tablist have too many problems
2. Chat is the easiest way, I think you can figure out a way to do it by yourself, you can get a player health via PlaceholderAPI (not sure though)
3. Scoreboard is not a bad idea but a lot of plugins already use it so I don't know if its a good idea :S

I can try to implement a thing like that when I will work on a scoreboard system ;)

**Comment by Tiplish** [comment]
The problem is, with a scoreboard system, if it's a team of 20 players for example, there is not enough place :p I would use this system for a MMORPG and raids. I suppose there is not easy way to show heal of groups :(

**Comment by AlessioDP** [comment]
You right, the tablist seems the better one but it isn't something that we can edit via the Bukkit API.
Maybe in the future we could edit it easily :) (with future Minecraft versions)

**Comment by Tiplish** [comment]
I hope o/ Maybe i will find a way to show HP in top of head of the players.
