### ISSUE TITLE
McMMO Party system blocks Parties usage

### ISSUE THREAD

**Issue by StevenGoh-YH** [AlessioDP/Parties#236]
Hi,

Parties is really awesome. However, I realised MCMMO 's integrated party system blocks out Parties usage.

Even after denying permissions for users to use MCMMO 's party, the /party cannot be registered during startup as MCMMO has already registered it beforehand.

**Comment by AlessioDP** [comment]
Hello, this is not a fixable issue of McMMO, there isn't a option to disable that system.

The only thing you can do is or remove McMMO or change Parties commands into something else. At the end of config.yml, you can change any command into whatever you prefer, for example: clan/guild/group/...
