### ISSUE TITLE
SkillApi+ConquestiaMobs

### ISSUE THREAD

**Issue by omatix** [AlessioDP/Parties#32]
There is a problem with getting shared exp with  SkillApi+ConquestiaMobs (Method: Exp_Bottle/Special. CQM dosen't support "MOB" table method 😢 ) 
It gets vanilla value instead of multiplier value from CQM. 

So for example it's 12 exp and 6 exp shared on 1st lvl Zombie. For 10th lvl it's 50 exp + still 6 exp shared via parties plugin. 😞 

Is it possible to add support for conquestiamobs? 
Maybe by placeholder %mob_level% for sharing formula?
Or just native support via integrating that together? 

there is a link
https://www.spigotmc.org/resources/conquestia-mobs.21307/

Thank you!

**Comment by AlessioDP** [comment]
Hi,
Unfortunately its not possible.

Conquestia Mobs doesn't have any API to hook for it.

**Comment by omatix** [comment]
Hmmm :C is it possible to lvlup just vanilla mobs with MythicMobs?

**Comment by AlessioDP** [comment]
I never used MythicMobs sorry :S

**Comment by omatix** [comment]
Okay thank you anyway ^ ^

**Comment by omatix** [comment]
I have one question. 
I'm able to re-edit conquestia mobs for personal use. Is it possible to hook into CQM script some parties Methods which decide about Skill-API experience share?

**Comment by AlessioDP** [comment]
I need to add some API methods for better exp handling, I will try to do it in a future version ;)

**Comment by omatix** [comment]
Okay I will keep my eyes on it! Thank you :D

**Comment by RacerN2O** [comment]
I just saw this and wanted to point out that it should be possible to have leveled vanilla mobs in MythicMobs.
