### ISSUE TITLE
Parties overwrites all other configs

### ISSUE THREAD

**Issue by Time6628** [AlessioDP/Parties#4]
This plugin overwrites most of the other plugins configs.
I'm going to guess this is because you use the Plugin object instead of the Parties object to handle your config,

**Comment by AlessioDP** [comment]
What are you talking about? Can you make some examples?

**Comment by Time6628** [comment]
The parties config is copied into multiple other plugin configs. 
You can test it out by installing the Statz plugin(https://github.com/Staartvin/Statz). If you look in the Statz config, it will be that parties config.

**Comment by AlessioDP** [comment]
I cannot replicate this bug.
Can you tell me version of spigot/bukkit, list of plugins and when this bug happens?

**Comment by Time6628** [comment]
I use Thermos, the continuation of cauldron for 1.7.10 https://github.com/CyberdyneCC/Thermos.
This occurs on startup.

**Comment by AlessioDP** [comment]
Tried, everything okay.
Tested on Thermos 1614 (1.7.10) with Statz and Parties 1.6.5.

**Comment by Time6628** [comment]
Did you try it without having the configs generated already? That's when it appears most for me.

**Comment by AlessioDP** [comment]
I tried with a full clean setup. (Only parties config too)

Did you tried only parties and statz with latest server build?
