### ISSUE TITLE
Conflict with PlotSquare

### ISSUE THREAD

**Issue by fmohican** [AlessioDP/Parties#47]
Hello!
I recently configure a server with plotsquared and Parties,
When i added Parties to server i get overwrite over all plotsquared commands, PlotSquared isn't work at all and there are no errors in console, only a warning from parties
```
[15:12:34 INFO]: [Parties] Enabling Parties v2.6.2
[15:12:34 INFO]: [Parties] Initializing Parties 2.6.2
[15:12:34 INFO]: [com.zaxxer.hikari.HikariDataSource] parties - Starting...
[15:12:34 INFO]: [com.zaxxer.hikari.HikariDataSource] parties - Start completed.
[15:12:34 WARN]: [Parties] 'p' was registered by another plugin, trying to overwrite it. If you have any problem you should change it
[15:12:34 INFO]: [Parties] Hooked into EssentialsChat
[15:12:34 INFO]: [Parties] Hooked into PlaceholderAPI
[15:12:34 INFO]: [Parties] Hooked into Vault
[15:12:34 INFO]: [Parties] Parties v2.6.2 enabled
```
It's right, plotsquared uses `p`, but pirates overwrite all `plot`, `plotsquared`, `plotme`

![image](https://user-images.githubusercontent.com/8583317/63691138-1d20c280-c817-11e9-8f15-312b3b1fbcf9.png)

**Comment by AlessioDP** [comment]
Hello,
Its normal overwrite every command because PlotSquared uses /p as alias, so if I overwrite it, of course I will overwrite the entire command (because its one).

The only thing that you can do its change /p into something else, its written into the log message.
There is no way to fix it, the problem its that PlotSquared does not allow you to change/edit commands.

**Comment by fmohican** [comment]
There its an way to fix, to remove `/p` from Parties, or atleast to put it optional....

**Comment by AlessioDP** [comment]
Its optional, you can change it. Just edit last lines of config.yml

**Comment by fmohican** [comment]
> Its optional, you can change it. Just edit last lines of config.yml

Probability i'm just mad, where is that magic config?
https://gist.github.com/fmohican/0504480f39651e9b118f90f018149cb1
This my actual config... I rename every "p" to "partyes", but isn't work actually.
Also please ignore database config [censored]...

**Comment by AlessioDP** [comment]
Line 322, you cannot edit the YAML keys but only values, so just edit the text inside double quotes.

**Comment by fmohican** [comment]
Good i will regen config, and come with reply if it's work.

**Comment by fmohican** [comment]
Thanks for help, yes it's work as you said.

Thanks again and sorry for bother you.

**Comment by AlessioDP** [comment]
Perfect :wink:
