### ISSUE TITLE
/back not supported for the home command.

### ISSUE THREAD

**Issue by d00mfish** [AlessioDP/Parties#55]
Thats a problem quite a few players on our server have already complained about.
When standing somewhere in your world and then teleport to spawn and then go to your party home, with /back you'll end up back on the first location and not spawn what should be your tp back location in this case. I hope it is somewhat understandable.
(somewhere) ->[/spawn]-> (spawn) ->[/party home]-> (party home) -> [/back]-> (somewhere) <- not spawn.

Oh and I keep getting the message on login: "The configuration file 'messages.yml' of Parties is outdated!" I could just change the version number in the messages.yml but that is probably not the intendet way.

Keep up the great work!

**Comment by AlessioDP** [comment]
Thank you for the report, 2 things:
1. With `/back`, you wanna go back where you performed `/party home` or `/spawn`? I don't directly support it but I can check if EssentialsX have some API to handle that
2. That message is used to alert you that there are some changes in the configuration file, you can or delete and regenerate the file or just add what changed. You can find the configuration file into this repository under `bukkit(or bungeecord)/src/main/resources/bukkit(or bungee)/messages.yml`

**Comment by d00mfish** [comment]
Wow thanks a lot for the quick response.

1. with `/back` I want to go back to where I performed `/party home` so you can switch between two locations when typing `/back` repeatedly. 
Since probably most servers out there use EssentialsX it would be great if you can take a look into that.

2.Ok thank you I think I'll try it with regenerating.

**Comment by AlessioDP** [comment]
The update is complete, I'm just looking for something else to fix. I will release it really soon ;)

**Comment by d00mfish** [comment]
Oh cool thanks for all the Work you put into it :D
