### ISSUE TITLE
Null when player is offline

### ISSUE THREAD

**Issue by Feerko** [AlessioDP/Parties#6]
Hello, 

i'm using your Parties. This plugin is awesome. I'm using it on my mini games on bungeecord. 

There is one issue. When I type /party members it's sometimes return 'null', so can you store a player nickname in db?

Thanks! :)

**Comment by AlessioDP** [comment]
Hi, can you attach the log of the server? I need to see the error.

**Comment by Feerko** [comment]
<img width="389" alt="zrzut ekranu 2017-07-21 o 09 38 58" src="https://user-images.githubusercontent.com/16988054/28456311-3202e9d8-6e02-11e7-9022-791a1a36b233.png">

my servers are restarting everyday at 04:30 and all userdata are deleted so server doesn't know name of player.

**Comment by AlessioDP** [comment]
Right now it's impossible to fix but with the new update there is some changes about how the data of a player is stored so I will fix this ;)

**Comment by Feerko** [comment]
Ok, thanks :)

**Comment by AlessioDP** [comment]
Implemented with 2.0.0.
