### ISSUE TITLE
[1.8] Parties giving error on startup

### ISSUE THREAD

**Issue by Zenya4** [AlessioDP/Parties#63]
I am unable to use the parties plugin and it gives an error on startup

https://hasteb.in/mosicugo.lua

ver output: This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by AlessioDP** [comment]
Do not reload the plugin with PlugMan, it is not able to start it correctly. :wink:

**Comment by Zenya4** [comment]
Yea but when I load it normally from startup, it gives me the message that the /party command does not exist, even though the command shows in /help party

**Comment by AlessioDP** [comment]
Can you post here your full server log?

**Comment by Zenya4** [comment]
Sure thing, I’ll send you a hastebin log of me starting and stopping the server tomorrow after I whitelist my server so that no IPs are leaked. Also, can I trouble you to re-open this issue report?

**Comment by AlessioDP** [comment]
I will reopen it but the issue is not the first anymore :P

Do not just stop and start it, try to use a command too

Feel free to edit the log and hide any private information!

**Comment by Zenya4** [comment]
Hi there @AlessioDP ,

My apologies for the late reply. You can find my server log uploaded here https://hasteb.in/ogiqodod.md

I have a feeling that it may have something to do with the McDuels plugin as I set a config option to disable the `/party` command in that plugin so that Parties will override it. However, I think what what McDuels does is that it unregisters the `/party` command completely which breaks Parties.

If I leave the disable option to false, McDuels will take priority and override Parties for `/party`. I understand that the `/party` command can be changed to other keywords but I want it to remain as "party". Would it be possible if you made the Parties plugin load before McDuels (see https://www.spigotmc.org/wiki/plugin-yml/ , in `loadbefore`) so that the command from Parties can take priority over that of McDuels?

Thank you very much for your prompt response.

**Comment by AlessioDP** [comment]
I don't like this way to fix something, maybe you should ask to McDuels developer to fix this problem (?)

Anyway, try to open the .jar and change the plugin.yml according to your problem, try both loadbefore and softdepend, let me know if it works ;)

**Comment by Zenya4** [comment]
Sure thing, I’ll try doing that since it’s open source. Thanks for the support!
