### ISSUE TITLE
Party Teleport

### ISSUE THREAD

**Issue by ArcticRaven** [AlessioDP/Parties#64]
When parties are teleported to a new world, the rest of the party is move to the world spawn and not the location that the player went to. 

https://i.imgur.com/OR3D9Rg.mp4

**Comment by AlessioDP** [comment]
Is not a bug ;)

In `config.yml` at line 191~ you can decide which type of teleport use:
- 1 = Teleport into world spawn
- 2 = Teleport to the same point of the followed player
