### ISSUE TITLE
Connect between servers - spam

### ISSUE THREAD

**Issue by Feerko** [AlessioDP/Parties#7]
<img width="389" alt="zrzut ekranu 2017-07-21 o 09 38 58" src="https://user-images.githubusercontent.com/16988054/28453658-82aed7fc-6df8-11e7-9759-00e713d534df.png">

hello, when i connect with party to other server i get a lot of messages and tries to connect.
can you increase delay between connects?

**Comment by AlessioDP** [comment]
Hi, can you attach the log of the server and a guide to re-create the problem? :)

**Comment by Feerko** [comment]
i just connect to other server and there is a lot connections to server. 
There is a second issue. Players are teleport where player (not leader) change the server.

**Comment by Feerko** [comment]
I will try with 'needed-rank: 20'. I did not notice it. Excuse me.
