### ISSUE TITLE
BukkitPartiesPlayerPostJoinEvent not working

### ISSUE THREAD

**Issue by ThePlay3r** [AlessioDP/Parties#70]
I'm trying to implement a Parties support to my Fork of UhcCore and to do that, I tried to listen for Parties API's `BukkitPartiesPlayerPostJoinEvent`, but it doesn't seem to work properly?

This is my simple code I have:
```java
@EventHandler
    public void onPartyJoin(BukkitPartiesPlayerPostJoinEvent event){
        System.out.println("Party joined.");
        playersManager.assignPartyTeam(event.getPartyPlayer().getPlayerUUID(), event.getInviter());
    }
```

What I'm trying to accomplish is, when a Party connects to the server, using the follow feature, all the players will be assigned to the same team.
However, when I create a new party with my alt account, connect to the UHC Server, my alt "follows" me, but the the error doesn't seem to be fired (No `"Party joined."` message shows up in the console)

Am I perhaps using the event for not its intended purpose, or am I missing something?
I absolutely love your work on Parties and would really like to be able to use the API in the way I described above.

**Comment by AlessioDP** [comment]
I am currently working on the new API (Parties 3.0.0), so any fix of 2.X will be deprecated.

I will mark this as working on so I can check if it works once the new API is ready :)
