### ISSUE TITLE
Console spam error

### ISSUE THREAD

**Issue by lbrunton** [AlessioDP/Parties#71]
Hi,

Great plugin, really enjoy using it. I noticed this popping up in console often, and would like to know how to fix it?

>.... [04:39:44 WARN]: [Parties] Something gone wrong on calculate the level of 'sora': java.lang.NullPointerException

Thank you,

**Comment by AlessioDP** [comment]
Its a known bug of the custom experience level. It is already been fixed with the upcoming 3.0.0 :)
