### ISSUE TITLE
I could not find a downloadable site for partiesapi anywhere.

### ISSUE THREAD

**Issue by hhoa343** [AlessioDP/Parties#72]
When I connected the bedwars proxy to the parties an error occurred. information in the photo below. output message k found partiesApi I searched the net but couldn't find it. 
I installed the lastlogin api but still didn't solve it
![unknown](https://user-images.githubusercontent.com/76720413/103433186-88ef1880-4c1f-11eb-9791-556c93fefd0c.png)

please give me a solution to solve this problem. 
parties to the latest version. 
Proxy bedwars latest version.

**Comment by AlessioDP** [comment]
This is not an issue related to Parties I think.

You can join my Discord tho, I will try to help anyway.
