### ISSUE TITLE
Command to teleport players to leader

### ISSUE THREAD

**Issue by Feerko** [AlessioDP/Parties#8]
Sometimes players from party are on different servers and there is no command to teleport they to leader. 

On hypixel you can type /party warp and all of players redirecting to leader's server.

Would you be able to add it? That would be great. Thanks :)))

**Comment by AlessioDP** [comment]
Of course :)

**Comment by Feerko** [comment]
Helloooo I care about these functions, could you add them?

**Comment by AlessioDP** [comment]
Added in my to-do list ;)

**Comment by AlessioDP** [comment]
Implemented with 2.0.0.
