### ISSUE TITLE
Permissions bug on bungeecord

### ISSUE THREAD

**Issue by BurkenDev** [AlessioDP/Parties#84]
There seems to be a small bug. The permissions groups parties.admin.*/parties.user.* you've setup does not work when using the plugin on bungee cord. Took me about 2 months to find this out. Now it works when you specify each permission separately. But that's such a hassle. Maybe you can have a look at why that doesn't work properly on bungeecord.

**Comment by AlessioDP** [comment]
Sorry for this issue but its not a bug.

Bukkit have child permissions, so parties.user.* contains all user permissions. BungeeCord doesn't have this feature.

If you setup permissions via BungeeCord configs, you must insert them one by one. If you use a permission manager plugin, usually, they support wildcard permissions (like `partiese.user.*`)
