### ISSUE TITLE
Issues with leaving party to join another.

### ISSUE THREAD

**Issue by snomnomnom** [AlessioDP/Parties#87]
When a player has joined a party, they cannot leave the party. It will say they have left in chat, but when they try to join another it tells them they are already in a party.

https://user-images.githubusercontent.com/74738094/106631074-5022c600-6574-11eb-81b5-2236f764d68b.mp4

[log.txt](https://github.com/AlessioDP/Parties/files/5912750/log.txt)

**Comment by AlessioDP** [comment]
It seems a database issue, can you enable debug log and try that again?

Which version exactly it is? Which database? Server?

**Comment by snomnomnom** [comment]
I posted the debug log.

https://github.com/AlessioDP/Parties/files/5912750/log.txt

Version is: Parties-3.0.0-rc.3
I haven't changed any database settings so it is still being written to h2 flatfile.
I am using Mohist-1.12.2-8ad9a5f as my server file as I run a Pixelmon Server.

I can also include a list of mods/plugins installed if you need them.

The server i'm using to test this is a localhost testing server.

**Comment by AlessioDP** [comment]
I am not able to reproduce it, it works for me.
Can you attach your config.yml and parties.yml? What parties are these? Fixed or normal parties?

**Comment by snomnomnom** [comment]
[config.zip](https://github.com/AlessioDP/Parties/files/5936823/config.zip)

They are fixed parties, as I don't want them to disband when I leave them to create another.

Sorry for the delay, been crazy busy.

**Comment by AlessioDP** [comment]
I am not able to re-create the issue, I checked the code and my own log and everything is correct.

Just one thing I don't understand, I do not see database queries, maybe there is something wrong with H2 database. Can you try another db? And upload again a new debug log of you that leave + join a party?
