### ISSUE TITLE
No support for TitleManager

### ISSUE THREAD

**Issue by GMatrixGames** [AlessioDP/Parties#9]
Can you please add integration for TitleManager so I can have my custom tablist w/ the parties.

**Comment by AlessioDP** [comment]
You can use PlaceholderAPI to add Parties info inside TitleManager:
https://github.com/AlessioDP/Parties/wiki/Plugins-Supported#deluxechat--placeholderapi

**Comment by GMatrixGames** [comment]
I can't get it to work, It comes up with just having the placeholder, not the party itself

**Comment by AlessioDP** [comment]
Can you attach here your configuration? both Parties and TitleManager :)

**Comment by GMatrixGames** [comment]
[Configs.zip](https://github.com/AlessioDP/Parties/files/1309337/Configs.zip)

**Comment by GMatrixGames** [comment]
And I have PlaceholderAPI as well

**Comment by AlessioDP** [comment]
Your config is too much old, it seems you are using 1.5.X Parties.
You should update to the latest version and let him create new config.yml and messages.yml.

**Comment by GMatrixGames** [comment]
Thank-you so much, I'm actually making a public H4M server
