### ISSUE TITLE
Not all party features are available

### ISSUE THREAD

**Issue by b1ued3mon** [AlessioDP/Parties#96]
I have set perms so that everything can be used, but the ability to set a party home or to teleport to someone in your part, are all unknown commands.

**Comment by AlessioDP** [comment]
Not every option is enabled by default, take a look at `config.yml` and `parties.yml`.
Home and teleport system are one of these ;)

**Comment by b1ued3mon** [comment]
I had a look and i enabled a few options but none of whihc i think will work, also, how do I turn off party damage? Im able to hit other members of my party, i wish to disable friendly damage.

**Comment by AlessioDP** [comment]
They should work, about the party damage: its enabled by default (the protection), probably you have the bypass permission so you can hit your party members.

You can take a look to friendly fire protection options in `parties.yml`.

**Comment by b1ued3mon** [comment]
Ah thank you! I found it!

**Comment by b1ued3mon** [comment]
One more issue, now party isnt working at all on the server. the commands still show up when i type them out in game, but nothing happens. any ideas?
